-- 0003: demo seed — matches only (users/picks come from real traffic).
-- `league` stores the frontend tab slug (src/mock.ts LEAGUES ids).
insert into matches (sport, league, starts_at, status, clock, team_a, team_b) values
('soccer',  'ucl', now() - interval '67 minutes', 'live', '67''',
  '{"name":"Real Madrid","abbr":"RMA","color":"#FEBE10"}', '{"name":"Man City","abbr":"MCI","color":"#6CABDD"}'),
('soccer',  'ucl', now() + interval '4 hours', 'scheduled', 'in 4h',
  '{"name":"Arsenal","abbr":"ARS","color":"#EF3340"}', '{"name":"Bayern","abbr":"FCB","color":"#DC052D"}'),
('soccer',  'uel', now() + interval '7 hours', 'scheduled', 'in 7h',
  '{"name":"Roma","abbr":"ROM","color":"#8E1F2F"}', '{"name":"Porto","abbr":"POR","color":"#00428C"}'),
('soccer',  'uecl', now() + interval '1 day', 'scheduled', 'Tomorrow',
  '{"name":"Fiorentina","abbr":"FIO","color":"#5A2D82"}', '{"name":"AZ Alkmaar","abbr":"AZ","color":"#D0021B"}'),
('baseball','mlb', now() - interval '90 minutes', 'live', '6th',
  '{"name":"Dodgers","abbr":"LAD","color":"#005A9C"}', '{"name":"Yankees","abbr":"NYY","color":"#8895a7"}'),
('baseball','mlb', now() + interval '3 hours', 'scheduled', 'in 3h',
  '{"name":"Braves","abbr":"ATL","color":"#CE1141"}', '{"name":"Mets","abbr":"NYM","color":"#FF5910"}'),
('baseball','kbo', now() + interval '1 day', 'scheduled', 'Tomorrow',
  '{"name":"LG Twins","abbr":"LG","color":"#C30452"}', '{"name":"Doosan Bears","abbr":"OB","color":"#131230"}'),
('baseball','npb', now() + interval '9 hours', 'scheduled', 'in 9h',
  '{"name":"Hanshin Tigers","abbr":"HAN","color":"#FFDD00"}', '{"name":"Yomiuri Giants","abbr":"YOM","color":"#F97709"}'),
('basketball','nba', now() - interval '70 minutes', 'live', 'Q3',
  '{"name":"Celtics","abbr":"BOS","color":"#007A33"}', '{"name":"Nuggets","abbr":"DEN","color":"#0E2240"}'),
('basketball','nba', now() + interval '2 hours', 'scheduled', 'in 2h',
  '{"name":"Lakers","abbr":"LAL","color":"#552583"}', '{"name":"Thunder","abbr":"OKC","color":"#007AC1"}'),
('basketball','euro', now() + interval '6 hours', 'scheduled', 'in 6h',
  '{"name":"Fenerbahce","abbr":"FEN","color":"#FFDE00"}', '{"name":"Olympiacos","abbr":"OLY","color":"#D6001C"}'),
('basketball','kbl', now() + interval '1 day', 'scheduled', 'Tomorrow',
  '{"name":"Seoul SK","abbr":"SK","color":"#E4002B"}', '{"name":"Busan KCC","abbr":"KCC","color":"#003876"}'),
('ufc','ppv', now() + interval '2 hours', 'scheduled', 'in 2h',
  '{"name":"Volkanovski","abbr":"FEA","color":"#8895a7"}', '{"name":"Topuria","abbr":"FEA","color":"#D64550"}'),
('ufc','ppv', now() + interval '90 minutes', 'scheduled', 'in 90m',
  '{"name":"Adesanya","abbr":"MID","color":"#111827"}', '{"name":"Du Plessis","abbr":"MID","color":"#4A6FA5"}'),
('ufc','fn', now() + interval '5 days', 'scheduled', 'Sat',
  '{"name":"Cannonier","abbr":"MID","color":"#7A1F1F"}', '{"name":"Imavov","abbr":"IMA","color":"#2C4770"}'),
('ufc','dwcs', now() + interval '2 days', 'scheduled', 'Tue',
  '{"name":"Reyes","abbr":"LHW","color":"#5B4A8A"}', '{"name":"Da Silva","abbr":"LHW","color":"#1F6E5B"}');
